### ISSUE TITLE
Application crash on 'Enter Comment' dialog

### ISSUE THREAD

**Issue by Elthial** [uxmal/reko#1056]
Error occurs when attempting to add comment to finished code output (Reconstruct data types / last step)

System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'MixedCodeDataControl'.'

![image](https://user-images.githubusercontent.com/567527/124336174-e810f400-db94-11eb-8187-be98c9a1365c.png)

Call Stack:
```
Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.Controls.TextView.ChangeLayout() Line 456
Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.Controls.TextView.OnModelChanged(System.EventArgs e) Line 441
Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.Controls.TextView.Model.set(Reko.UserInterfaces.WindowsForms.Controls.TextViewModel value) Line 435
Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.Controls.MixedCodeDataControl.RefreshModel() Line 132
Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.Controls.MixedCodeDataControl.AnnotationChanged(object sender, System.EventArgs e) Line 148 
Reko.Core.dll!Reko.Core.EventEx.Fire(System.EventHandler eh, object sender) Line 35 
Reko.Core.dll!Reko.Core.AnnotationList.this[Reko.Core.Address].set(Reko.Core.Address addr, string value) Line 61 
Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.Forms.CommentFormInteractor.ModifyComment() Line 133 
Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.Forms.CommentFormInteractor.Close(bool save) Line 118 
Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.Forms.CommentFormInteractor.Text_KeyDown(object sender, Reko.Gui.Controls.KeyEventArgs e) Line 76 
Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.TextBoxWrapper.Text_KeyDown(object sender, System.Windows.Forms.KeyEventArgs e) Line 76
WindowsDecompiler.dll!Reko.WindowsDecompiler.Driver.Main(string[] args) Line 45
```

**Comment by uxmal** [comment]
I've been unable to reproduce this on my machine. Are you able to reproduce this at will?

**Comment by Elthial** [comment]
I am able to reproduce this at will as discussed and infact first attempt at placing a comment caused the issue

Exception message:
```
System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a disposed object.
Object name: 'MixedCodeDataControl'.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphics()
   at Reko.UserInterfaces.WindowsForms.Controls.TextView.ChangeLayout() in C:\repos\reko\src\UserInterfaces\WindowsForms\Controls\TextView.cs:line 456
   at Reko.UserInterfaces.WindowsForms.Controls.TextView.OnModelChanged(EventArgs e) in C:\repos\reko\src\UserInterfaces\WindowsForms\Controls\TextView.cs:line 441
   at Reko.UserInterfaces.WindowsForms.Controls.TextView.set_Model(TextViewModel value) in C:\repos\reko\src\UserInterfaces\WindowsForms\Controls\TextView.cs:line 435
   at Reko.UserInterfaces.WindowsForms.Controls.MixedCodeDataControl.RefreshModel() in C:\repos\reko\src\UserInterfaces\WindowsForms\Controls\MixedCodeDataControl.cs:line 132
   at Reko.UserInterfaces.WindowsForms.Controls.MixedCodeDataControl.AnnotationChanged(Object sender, EventArgs e) in C:\repos\reko\src\UserInterfaces\WindowsForms\Controls\MixedCodeDataControl.cs:line 148
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Reko.Core.EventEx.Fire(EventHandler eh, Object sender) in C:\repos\reko\src\Core\EventEx.cs:line 35
   at Reko.Core.AnnotationList.Remove(Address addr) in C:\repos\reko\src\Core\AnnotationList.cs:line 68
   at Reko.UserInterfaces.WindowsForms.Forms.CommentFormInteractor.ModifyComment() in C:\repos\reko\src\UserInterfaces\WindowsForms\Forms\CommentFormInteractor.cs:line 137
   at Reko.UserInterfaces.WindowsForms.Forms.CommentFormInteractor.Close(Boolean save) in C:\repos\reko\src\UserInterfaces\WindowsForms\Forms\CommentFormInteractor.cs:line 118
   at Reko.UserInterfaces.WindowsForms.Forms.CommentFormInteractor.Text_LostFocus(Object sender, EventArgs e) in C:\repos\reko\src\UserInterfaces\WindowsForms\Forms\CommentFormInteractor.cs:line 125
   at System.Windows.Forms.Control.OnLostFocus(EventArgs e)
   at System.Windows.Forms.Control.WmKillFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Elthial** [comment]
Of course the moment I say that it starts working perfectly vs previously were I was avoiding comments because of the crashes. 

Currently attempting to get repeatability steps:
* So far happens in long running sessions but trying to discover if certain combinations are cause.

**Comment by Elthial** [comment]
I cannot consistently reproduce, so will close this until I can get a reproducible error.
