### ISSUE TITLE
Analysis Error - Object not set to instance of object

### ISSUE THREAD

**Issue by Elthial** [uxmal/reko#1181]
Hello,

I was trying to run the most recent 0.11.1.0 release against the BTECH.exe and analysis appears appears to stop early before attempting to translate most of the code into high-level language.

This previously work at least further in 0.10.1.0, so appears to be a recent change.
(Reko has multiple issues with the 16-bit DOS / Assembly EXE that are unresolved)

Reko produces an "analysis_99_crash.txt" with the following contents:

`// fn207F_3EC4 ===========
Object reference not set to an instance of an object.
   at Reko.Analysis.SsaTransform.InsertAfterDefinition(Statement stmBefore, AliasAssignment ass)
   at Reko.Analysis.SsaTransform.FlagGroupTransformer.MakeSlice(ValueTuple``3 elem)
   at Reko.Analysis.SsaTransform.FlagGroupTransformer.ReadBlockLocalVariable(SsaBlockState bs)
   at Reko.Analysis.SsaTransform.IdentifierTransformer.ReadVariable(SsaBlockState bs)
   at Reko.Analysis.SsaTransform.IdentifierTransformer.<AddPhiOperands>b__17_0(Block p)
   at System.Linq.Enumerable.SelectListIterator``2.ToArray()
   at Reko.Analysis.SsaTransform.IdentifierTransformer.AddPhiOperands(SsaIdentifier phi)
   at Reko.Analysis.SsaTransform.IdentifierTransformer.ReadVariableRecursive(SsaBlockState bs)
   at Reko.Analysis.SsaTransform.FlagGroupTransformer.ReadBlockLocalVariable(SsaBlockState bs)
   at Reko.Analysis.SsaTransform.IdentifierTransformer.ReadVariable(SsaBlockState bs)
   at Reko.Analysis.SsaTransform.IdentifierTransformer.ReadVariableRecursive(SsaBlockState bs)
   at Reko.Analysis.SsaTransform.FlagGroupTransformer.ReadBlockLocalVariable(SsaBlockState bs)
   at Reko.Analysis.SsaTransform.IdentifierTransformer.ReadVariable(SsaBlockState bs)
   at Reko.Analysis.SsaTransform.<>c__DisplayClass25_0.<AddUsesToExitBlock>b__7(Statement u)
   at System.Collections.Generic.List``1.ForEach(Action``1 action)
   at Reko.Analysis.DataFlowAnalysis.ConvertToSsa(Procedure proc)`

`// fn207F_3EC4
// Return size: 4
define fn207F_3EC4
fn207F_3EC4_entry:
	def fp
	def cl
	def dx
	def ax
	sp_2 = fp
	Top_3 = 0<i8>
	// succ:  l207F_3EC4
l207F_3EC4:
	ch_4 = 0<8>
	SZO_5 = cond(0<8>)
	O_29 = SLICE(SZO_5, bool, 4) (alias)
	C_6 = false
	cx_8 = CONVERT(cl, byte, uint16) (alias)
	branch cx_8 == 0<16> l207F_3ECE
	// succ:  l207F_3EC8 l207F_3ECE
l207F_3EC8:
	cx_17 = PHI((cx_8, l207F_3EC4), (cx_18, l207F_3EC8))
	ax_12 = PHI((ax, l207F_3EC4), (ax_15, l207F_3EC8))
	dx_9 = PHI((dx, l207F_3EC4), (dx_10, l207F_3EC8))
	v13_21 = dx_9
	v9_13 = (ax_12 & 2<16>) != 0<16>
	v14_22 = ax_12
	v15 = SEQ(dx_9, ax_12) >>u 1<8>
	dx_10 = SLICE(v15, word16, 16)
	ax_15 = SLICE(v15, word16, 0)
	C_16 = v9_13
	cx_18 = cx_17 - 1<16>
	branch cx_18 != 0<16> l207F_3EC8
	// succ:  l207F_3ECE l207F_3EC8
l207F_3ECE:
	O_28 = PHI()
	dx_27 = PHI((dx, l207F_3EC4), (dx_10, l207F_3EC8))
	cx_26 = PHI((cx_8, l207F_3EC4), (cx_18, l207F_3EC8))
	C_25 = PHI((C_6, l207F_3EC4), (C_16, l207F_3EC8))
	ax_24 = PHI((ax, l207F_3EC4), (ax_15, l207F_3EC8))
	return
	// succ:  fn207F_3EC4_exit
fn207F_3EC4_exit:
	use ax_24
	use C_25
	use cx_26
	use dx_27
	use O
	use S
	use sp
	use Top
	use Z`

**Comment by uxmal** [comment]
I cannot make this reproduce in the current build -- have you tried downloading a nightly build from https://github.com/uxmal/reko/actions/runs/2434730088 ?

**Comment by Elthial** [comment]
I did not, I have just tested with the nightly build and the above error is resolved.
I will close this ticket
