### ISSUE TITLE
[Dll decomp] - Viewing properties results in unhandled exception

### ISSUE THREAD

**Issue by RivenSkaye** [uxmal/reko#1352]
When decompiling a DLL right-clicking the DLL name and hitting properties causes a crash due to Splat not being found.

Stakctrace:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'Splat, Version=14.6.0.0, Culture=neutral, PublicKeyToken=null'. Het systeem kan het opgegeven bestand niet vinden.
File name: 'Splat, Version=14.6.0.0, Culture=neutral, PublicKeyToken=null'
   at Reko.UserInterfaces.WindowsForms.Forms.ProgramPropertiesInteractor.Attach(ProgramPropertiesDialog dlg)
   at Reko.UserInterfaces.WindowsForms.Forms.ProgramPropertiesDialog..ctor(ProgramPropertiesInteractor interactor)
   at Reko.UserInterfaces.WindowsForms.Forms.ProgramPropertiesDialog..ctor()
   at Reko.UserInterfaces.WindowsForms.WindowsFormsDialogFactory.CreateProgramPropertiesDialog(Program program)
   at Reko.Gui.Design.ProgramDesigner.ExecuteAsync(CommandID cmdId)
   at Reko.Gui.Services.ProjectBrowserService.ExecuteAsync(CommandID cmdId)
   at Reko.Gui.Forms.MainFormInteractor.ExecuteAsync(CommandID cmdId)
   at Reko.UserInterfaces.WindowsForms.Controls.MenuSystem.item_Click(Object sender, CommandMenuEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

***** Loaded assemblies snipped off for brevity *****
```

**Comment by uxmal** [comment]
Thanks for reporting this. Apparently recent builds of System.Windows.Forms are requiring the `Splat` assembly. I hadn't been aware of this. I will be adding Splat to the Reko installer package shortly.

**Comment by RivenSkaye** [comment]
I'll poke the same project monday and reopen the issue when the next thing is unexpectedly broken

**Comment by RivenSkaye** [comment]
Everything seems to work like a charm!
