### ISSUE TITLE
System.InvalidCastException on x86 DOS .exe

### ISSUE THREAD

**Issue by fenugrec** [uxmal/reko#424]
Hi,
using the latest 0.6.2 msi available on sourceforge, I'm having this problem :

- load a 16-bit DOS .exe ( this one, https://filebin.net/a6f0c1gpdfxf5v5r ) ;
- click "Action -> Next phase", try to browse around
- if I select any of the automatically-named functions (say, fn0800_01B4), reko works for a few seconds and then I get this .NET exception window (reko doesn't crash however) : 

(I trimmed the detailed version information at the end)
```
************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'Reko.Gui.Windows.Controls.EmptyEditorModel' to type 'Reko.Gui.Windows.Controls.MixedCodeDataModel'.
   at Reko.Gui.Windows.CombinedCodeViewInteractor.MixedCodeDataView_TopAddressChanged()
   at Reko.Gui.Windows.CombinedCodeViewInteractor.CombinedCodeView_CurrentAddressChanged(Object sender, EventArgs e)
   at Reko.Core.EventEx.Fire(EventHandler eh, Object sender)
   at Reko.Gui.Windows.Controls.CombinedCodeView.set_CurrentAddress(Address value)
   at Reko.Gui.Windows.CombinedCodeViewInteractor.set_SelectedAddress(Address value)
   at Reko.Gui.Windows.CombinedCodeViewInteractor.DisplayProcedure(Program program, Procedure proc)
   at Reko.Gui.Windows.CodeViewerServiceImpl.DisplayProcedure(Program program, Procedure proc)
   at Reko.Gui.Design.ProcedureDesigner.DoDefaultAction()
   at Reko.Gui.ProjectBrowserService.tree_AfterSelect(Object sender, EventArgs e)
   at Reko.Core.EventEx.Fire(EventHandler eh, Object sender)
   at Reko.Gui.Windows.Controls.TreeViewWrapper.treeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/WINDOWS/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WindowsDecompiler
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///D:/dev/reko/WindowsDecompiler.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Reko.Gui
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///D:/dev/reko/Reko.Gui.DLL
----------------------------------------
Reko
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///D:/dev/reko/Reko.DLL
----------------------------------------
Reko.Core
    Assembly Version: 0.6.2.0
    Win32 Version: 0.6.2.0
    CodeBase: file:///D:/dev/reko/Reko.Core.DLL
----------------------------------------
```

**Comment by ptomin** [comment]
The reason of problem is `OutOfMemoryException`. PR #425 contains workaround for it.

**Comment by ptomin** [comment]
@uxmal merged my workaround to `master`.
@fenugrec could you build `master` branch? If not, @uxmal could provide installer for you.

**Comment by ptomin** [comment]
It was fixed by 4e53817. Is not it John?

**Comment by uxmal** [comment]
@ptomin I have to verify this first. I will probably do that tonight or tomorrow.

**Comment by fenugrec** [comment]
Tested with latest msi (0.7.1.0), issue is fixed. Thanks !
