### ISSUE TITLE
System.NullReferenceException in MixedCodeDataModel.CreateSpanifier when scrolling

### ISSUE THREAD

**Issue by petsuter** [uxmal/reko#827]
Using the current build from AppVeyor (a7a19310d2dd557a2defe0f1b4a31e9d96f55d0c) I got this exception when scrolling:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Reko.UserInterfaces.WindowsForms.Controls.MixedCodeDataModel.CreateSpanifier(ImageMapItem item, ModelPosition pos) in C:\projects\reko\src\UserInterfaces\WindowsForms\Controls\MixedCodeDataModel.SpanGenerator.cs:line 129
   at Reko.UserInterfaces.WindowsForms.Controls.MixedCodeDataModel.GetLineSpans(Int32 count) in C:\projects\reko\src\UserInterfaces\WindowsForms\Controls\MixedCodeDataModel.SpanGenerator.cs:line 58
   at Reko.UserInterfaces.WindowsForms.Controls.TextViewLayout.VisibleLines(TextViewModel model, Size size, Graphics g, Font defaultFont, StyleStack styleStack) in C:\projects\reko\src\UserInterfaces\WindowsForms\Controls\TextViewLayout.cs:line 88
   at Reko.UserInterfaces.WindowsForms.Controls.TextView.ComputeLayout(Graphics g) in C:\projects\reko\src\UserInterfaces\WindowsForms\Controls\TextView.cs:line 360
   at Reko.UserInterfaces.WindowsForms.Controls.TextView.RecomputeLayout() in C:\projects\reko\src\UserInterfaces\WindowsForms\Controls\TextView.cs:line 534
   at Reko.UserInterfaces.WindowsForms.Controls.TextView.vScroll_ValueChanged(Object sender, EventArgs e) in C:\projects\reko\src\UserInterfaces\WindowsForms\Controls\TextView.cs:line 510
   at System.Windows.Forms.ScrollBar.OnValueChanged(EventArgs e)
   at System.Windows.Forms.ScrollBar.set_Value(Int32 value)
   at System.Windows.Forms.ScrollBar.DoScroll(ScrollEventType type)
   at System.Windows.Forms.ScrollBar.WmReflectScroll(Message& m)
   at System.Windows.Forms.ScrollBar.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Diagnostics:
```
Warning,0C37:0D68,Procedure fn0C37_0D65 previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0BD5:016B,Procedure fn0BD5_0145 previously had a return address of 2 bytes on the stack, but now seems to have a return address of 4 bytes on the stack.
Warning,0C37:106B,Procedure fn0C37_1060 previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:106B,Procedure fn0C37_1060 previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:1062,Procedure fn0C37_1060 previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:00D3,Procedure fn0C37_020E previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:12D8,Procedure fn0C37_12D1 previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:139B,Procedure fn0C37_138D previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:139B,Procedure fn0C37_138D previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:138F,Procedure fn0C37_138D previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:072C,Procedure fn0C37_071E previously had a return address of 2 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:0731,Procedure fn0C37_071E previously had a return address of 2 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:0747,Procedure fn0C37_0735 previously had a return address of 0 bytes on the stack, but now seems to have a return address of 2 bytes on the stack.
Warning,0C37:0FFD,Procedure fn0C37_0FD8 previously had a return address of 2 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0C37:0FFD,Procedure fn0C37_0FD8 previously had a return address of 2 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0800:3BCF,Procedure fn0BBC_0000 previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Warning,0BBC:0001,Procedure fn0BBC_0000 previously had a return address of 4 bytes on the stack, but now seems to have a return address of 0 bytes on the stack.
Error,0800:1983,An error occurred while processing the statement Mem136[ds_111:0x0954:word16] = SLICE(es_ax_126, selector, 16) - (ax_129 <u 0x0005). Not handling (ptr16 (segment)) and bool yet. 
Error,0800:229F,An error occurred while processing the statement Mem89[ds:0x0954:word16] = SLICE(es_ax_79, selector, 16) - (ax_82 <u 0x0001). Not handling (ptr16 (segment)) and bool yet. 
Error,0C37:0914,An error occurred while processing the statement return di_116 - di. Not handling (memptr T_16919 (struct 0001 (0 byte b0000))) and (memptr T_16919 (struct (0 T_16937 t0000))) yet. 
Error,0C37:0AC0,An error occurred while processing the statement return di_209 - di. Not handling (memptr T_17010 (struct 0001 (0 byte b0000))) and (memptr T_17010 (struct (0 T_17077 t0000))) yet. 
Warning,,Selector 0040 has no known segment.
Warning,,Selector 0000 has no known segment.
```

**Comment by uxmal** [comment]
I need access to the binary that is causing the problem. You can contact me on gitter.im if necessary

**Comment by petsuter** [comment]
http://vadim.oversigma.com/Tetris3.zip

**Comment by uxmal** [comment]
Commit 3f7d5bf fixes this issue.
