### ISSUE TITLE
System.OverflowException: Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#914]
Reko throws exception during analysis phase on my binaries:
```
error: An error occurred during decompilation. System.OverflowException: Arithmetic operation resulted in an overflow.
at System.Convert.ToUInt64(Double value)
at Reko.Core.Expressions.ConstantReal64.ToUInt64() in d:\dev\uxmal\reko\master\src\Core\Expressions\Constant.cs:line 1757
at Reko.Evaluation.SliceConstant_Rule.Transform() in d:\dev\uxmal\reko\master\src\Decompiler\Evaluation\SliceConstant_Rule.cs:line 45
at Reko.Evaluation.ExpressionSimplifier.VisitSlice(Slice slice) in d:\dev\uxmal\reko\master\src\Decompiler\Evaluation\ExpressionSimplifier.cs:line 871
at Reko.Core.Expressions.Slice.AcceptT in d:\dev\uxmal\reko\master\src\Core\Expressions\Slice.cs:line 64
at Reko.Analysis.ValuePropagator.VisitAssignment(Assignment a) in d:\dev\uxmal\reko\master\src\Decompiler\Analysis\ValuePropagator.cs:line 103
at Reko.Core.Code.Assignment.AcceptT in d:\dev\uxmal\reko\master\src\Core\Code\Assignment.cs:line 49
at Reko.Analysis.ValuePropagator.Transform(Statement stm) in d:\dev\uxmal\reko\master\src\Decompiler\Analysis\ValuePropagator.cs:line 95
at Reko.Analysis.ValuePropagator.Transform() in d:\dev\uxmal\reko\master\src\Decompiler\Analysis\ValuePropagator.cs:line 86
at Reko.Analysis.DataFlowAnalysis.ConvertToSsa(Procedure proc) in d:\dev\uxmal\reko\master\src\Decompiler\Analysis\DataFlowAnalysis.cs:line 490
```
I suggest to introduce new method `int64 Constant.ToBitPattern()` which does reinterpret cast (e. g. for `1.0` returns `0x3ff0000000000000` instead of `0x1`) and use it instead of `ToInt64` in `ExpressionSimplifier`

**Comment by uxmal** [comment]
Could you hunt down the expression that exhibits this behavior? Let's put it under unit test and see how to fix it now that `Convert` expressions are available.

**Comment by ptomin** [comment]
OK. I'll try to create unit test

**Comment by ptomin** [comment]
John, is not following lines
https://github.com/uxmal/reko/blob/a822a0a45e523cb099ed1d37e48964ea96859260/src/Decompiler/Evaluation/ExpressionSimplifier.cs#L937-L946
do the same thing as `SliceConstant_Rule `?

**Comment by uxmal** [comment]
This crash should have gone away after commit 5ed85bf9e27d98dafc79f0b75a8aabef0acb1144.

**Comment by ptomin** [comment]
Thanks, John!
